### ISSUE TITLE
Input prodigal GFF/output prophage call in GFF format?

### ISSUE THREAD

**Issue by jdwinkler-lanzatech** [bobeobibo/phigaro#10]
Hi,

Thanks for your work on this tool-just found it in a search for prophage annotation pipelines and I like your approach versus the other tools in the field. Some request that would make it easier to integrate into our annotation pipeline, if possible:

1. Is it possible to provide the Prodigal annotations as an input? We already routinely run prodigal, so it would be helpful to avoid duplication.
2. Is it possible to output a GFF file with the prophage calls in addition to html/tsv?

No worries if these are not possible.

**Comment by PollyTikhonova** [comment]
I'm very sorry for long time no answer, I was intended to implement the features you asked for, but occasionally it took much mofre time then I realized. So, I wanted to say that I heard you we are in process.
By the way, thanks for your feedback! Stay tuned)

**Comment by jdwinkler-lanzatech** [comment]
No problem! Thank you for your help.

**Comment by PollyTikhonova** [comment]
Do you mean that gff file should contain data about genes from prophage regions? or just info about start and end of a prophage in a gff format?

**Comment by jdwinkler-lanzatech** [comment]
I think I meant just start, stop orientation (if possible), and then maybe the name/p-value of the best match in the info section?

**Comment by PollyTikhonova** [comment]
Outputs in gff and bed formats are implemented in version 2.1.9

**Comment by jdwinkler-lanzatech** [comment]
Thank you! I'll give it a shot in the next few days.

**Comment by jdwinkler-lanzatech** [comment]
Hi, apologies for the (massively) delayed response. Works great for me!

**Comment by PollyTikhonova** [comment]
@jdwinkler-lanzatech glad to hear that!
