### ISSUE TITLE
Remove Error for sequences < 20000 bp

### ISSUE THREAD

**Issue by vinisalazar** [bobeobibo/phigaro#14]
Hi,

I'm trying to run Phigaro in batch from custom scripts, but I am failing because it gives me the following message:

```
Error! Your fasta file contains at least one sequence length < 20000.  The short sequences are:

Do you want to start Phigaro without these sequences? [Y/n]
```

This is causing me to have to filter these sequences prior to running Phigaro. Would it be able to implement an argument to the main Phigaro CLI script to simply ignore this error? Any workarounds are appreciated :)

Thank you for any assistance you can provide,

V

**Comment by PollyTikhonova** [comment]
At version 2.1.9 you can find the parameter -d or --delete-shorts that allows you to exclude short sequences automatically.
