### ISSUE TITLE
Using phigaro via conda

### ISSUE THREAD

**Issue by chris-rands** [bobeobibo/phigaro#16]
People might find it easier to install phigaro via conda, we could document how to do this. Here is a lightweight way:

```
conda env create -f environment.yml
conda activate phigaro_env
```

Where `environment.yml` contains:
```
name: phigaro_env
dependencies:
  - python=3.7
  - pip
  - prodigal
  - hmmer
  - pip:
    - phigaro
```

Then run `phigaro-setup`

**Comment by PollyTikhonova** [comment]
Oh, that's a good idea! I'll add this, thank you!
