### ISSUE TITLE
Are there plans to submit Phigaro to Bioconda?

### ISSUE THREAD

**Issue by rpetit3** [bobeobibo/phigaro#25]

**Comment by chris-rands** [comment]
I agree that we should put Phigaro on Bioconda. However, in the mean time you can easily create a conda environment with: https://github.com/bobeobibo/phigaro/blob/master/environment.yml

Also, Polina recently added Docker and Singularity files, so that is another option for you

**Comment by vinisalazar** [comment]
@rpetit3 I can get this started but would need one of the main developers to step up as a maintainer for the Conda recipe. @bobeobibo would it be possible?

Thanks :)

**Comment by PollyTikhonova** [comment]
@vinisalazar Hello, I am the main dev of the Phigaro. @rpetit3 I am sorry for the delay but I was distracted by other things. I am in proccess of uploading Phigaro to bioconda. I'll do it in the next couple of days.

**Comment by vinisalazar** [comment]
awesome, thanks @PollyTikhonova

**Comment by PollyTikhonova** [comment]
@rpetit3 @vinisalazar @tauqeer9 Happy to announce that I pushed Phigaro to bioconda and now, I am waiting for merging
https://github.com/bioconda/bioconda-recipes/pull/24286
Sorry for the delay, it was a bit tricky to add a non-conda requirement, but finally, I nailed it)

**Comment by rpetit3** [comment]
Very exciting news! Thank you very much @PollyTikhonova !

**Comment by PollyTikhonova** [comment]
Just wanted to notify that it was merged and is now available at https://anaconda.org/bioconda/phigaro
