### ISSUE TITLE
Unable to run `sudo phigaro-setup`

### ISSUE THREAD

**Issue by gabriellovate** [bobeobibo/phigaro#27]
(phigaro) ➜  ~ sudo phigaro-setup                             
sudo: phigaro-setup: command not found

**Comment by gabriellovate** [comment]
I didn´t have locate

**Comment by PollyTikhonova** [comment]
Please, follow the manual setup instructions https://phigaro.readthedocs.io/en/latest/getting_started/#installation:
you need to download hmms,  copy `config.yml`, change paths of hmmer and prodigal, write a path to the downloaded hmms and put this file to `$HOME/.phigaro` directory.

**Comment by gabriellovate** [comment]
@PollyTikhonova the problem was that I did not have `locate` installed. Sorry for bothering you and thank you for the support.

**Comment by PollyTikhonova** [comment]
No problem, just thought that maybe you did not have an opportunity to install l`ocate`
