### ISSUE TITLE
pvog database link not working

### ISSUE THREAD

**Issue by Handymanalan** [bobeobibo/phigaro#28]
Hi Polly,

I was trying to download the pvog database to setup phigaro but this link is not working (http://download.ripcm.com/phigaro/).

Is there another way to download pvog and setup phigaro?

Cheers

Alan

**Comment by PollyTikhonova** [comment]
Hello, @Handymanalan

Give me your email, I'll send it to you directly now.
I'll figure out the problem next week with the link

**Comment by Handymanalan** [comment]
Here's my email: h.l.wong@unsw.edu.au

Thanks!
