### ISSUE TITLE
phigaro-setup - non-interactive setup possible?

### ISSUE THREAD

**Issue by rpetit3** [bobeobibo/phigaro#29]
Hello!

Is there a built-in method to skip the "please select appropriate "x" location" prompts during setup?

```
...
Please select appropriate Prodigal location
[1] /local/home/rpetit/miniconda3/envs/bt-phigaro/bin/prodigal
[2] Add another path manually
Choose your option (Enter for /local/home/rpetit/miniconda3/envs/bt-phigaro/bin/prodigal):
Please select appropriate HMMER location
[1] /local/home/rpetit/miniconda3/envs/bt-phigaro/bin/hmmsearch
[2] Add another path manually
Choose your option (Enter for /local/home/rpetit/miniconda3/envs/bt-phigaro/bin/hmmsearch):
Found Prodigal in: /local/home/rpetit/miniconda3/envs/bt-phigaro/bin/prodigal
Found HMMER in: /local/home/rpetit/miniconda3/envs/bt-phigaro/bin/hmmsearch
...
```

Thank you!

**Comment by PollyTikhonova** [comment]
Not for now. Is it neccessary?

**Comment by rpetit3** [comment]
Probably not necessary, but would be useful.

I'm building a Nextflow workflow for Phigaro using the conda build. It would be useful to just run `phigaro-setup` without interacting since Prodigal and HMMER will always be available.

As an alternative, if a config file is provided does it use the provided paths or also ask to verify? (I can check shortly)

**Comment by PollyTikhonova** [comment]
As far as I remember it does not ask to verify

**Comment by rpetit3** [comment]
Ok, so here's what I'm doing to allow "non-interactive" setup of databases.

```
rm -rf .phigaro/* && printf '\n\nN\n' | phigaro-setup --no-updatedb
```

This would allow the database to at least be setup in a programmatic way (e.g. in a workflow).

Going to close this issue.

**Comment by iferres** [comment]
+1 for non-interactive setup
