### ISSUE TITLE
Empty output file in some genomes

### ISSUE THREAD

**Issue by Daikuang** [bobeobibo/phigaro#30]
Hello,

I tried to use this tool to predict prophage in different strains. It works in most strains. however, in some strains I can't get any results (with an empty output) and come out a problem as shown below. I am preety show that these genomes are good, and I can get results when I tried other tools. I will very appreciate help me to figure out what's the issue.

Thanks
Dai

Traceback (most recent call last):
  File "/home/kuangdai/.local/bin/phigaro", line 8, in <module>
    sys.exit(main())
  File "/home/kuangdai/.local/lib/python3.8/site-packages/phigaro/cli/batch.py", line 246, in main
    task_output_file = run_tasks_chain(tasks)
  File "/home/kuangdai/.local/lib/python3.8/site-packages/phigaro/batch/runner.py", line 20, in run_tasks_chain
    task.run()
  File "/home/kuangdai/.local/lib/python3.8/site-packages/phigaro/batch/task/hmmer.py", line 27, in run
    self.hmmer(
  File "/home/kuangdai/.local/lib/python3.8/site-packages/sh.py", line 1520, in __call__
    return RunningCommand(cmd, call_args, stdin, stdout, stderr)
  File "/home/kuangdai/.local/lib/python3.8/site-packages/sh.py", line 784, in __init__
    self.wait()
  File "/home/kuangdai/.local/lib/python3.8/site-packages/sh.py", line 841, in wait
    self.handle_command_exit_code(exit_code)
  File "/home/kuangdai/.local/lib/python3.8/site-packages/sh.py", line 865, in handle_command_exit_code
    raise exc
sh.SignalException_SIGSEGV: 

  RAN: /home/kuangdai/miniconda3/bin/hmmsearch --cpu 16 --notextw --tblout proc/hmmer/A255-6fe68ffa37454fa3bfce47431d78c54f.hmmer_out /home/kuangdai/.phigaro/pvog/allpvoghmms proc/prodigal/A255-6fe68ffa37454fa3bfce47431d78c54f.faa

  STDOUT:
# hmmsearch :: search profile(s) against a sequence database
# HMMER 3.3.1 (Jul 2020); http://hmmer.org/
# Copyright (C) 2020 Howard Hughes Medical Institute.
# Freely distributed under the BSD open source license.
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# query HMM file:                  /home/kuangdai/.phigaro/pvog/allpvoghmms
# target sequence database:        proc/prodigal/A255-6fe68ffa37454fa3bfce47431d78c54f.faa
# per-seq hits tabular output:     proc/hmmer/A255-6fe68ffa37454fa3bfce47431d78c54f.hmmer_out
# max ASCII text line length:      unlimited
# number of worker threads:        16
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

Query:       VOG0001  [M=98]
Scores for co... (12411522 more, please see e.stdout)

  STDERR:

**Comment by PollyTikhonova** [comment]
Hello @Daikuang! 
Thank you very much for using our tool!
Could you, please, send me the files/strains that cause the problems?
You can send them privately to my email tikhonova.polly@mail.ru

**Comment by PollyTikhonova** [comment]
Dear @Daikuang , it seems as it's an internal hmmsearch v3.3.1 problem. I've tested different versions of it and run hmmsearch command itself - 3.3.2 and 3.2.1 and other really old versions work fine, while hmmsearch v3.3.1 corrupts at some point. According to bioconda files at anaconda server they were aware of this problem and tried to fix it but dropped the wrong version number (that's my speculations).
So, I advise you just to upgrade or downgrade your hmmer.
Please, do not hesitate to write me, if the problem will remain or you meet with other issues.

**Comment by Daikuang** [comment]
Thank you so much for your kind help and advice. I will try this soon.

Dai



At 2021-03-09 19:43:20, "Polina" <notifications@github.com> wrote:

Dear @Daikuang , it seems as it's an internal hmmsearch v3.3.1 problem. I've tested different versions of it and run hmmsearch command itself - 3.3.2 and 3.2.1 and other really old versions work fine, while hmmsearch v3.3.1 corrupts at some point. According to bioconda files at anaconda server they were aware of this problem and tried to fix it but dropped the wrong version number (that's my speculations).
So, I advise you just to upgrade or downgrade your hmmer.
Please, do not hesitate to write me, if the problem will remain or you meet with other issues.

**Comment by miasungeunlee** [comment]
Dear @PollyTikhonova 
Thank you for developping this great tool ! 
@Daikuang Did you figure out the issue ? 
I have same issue, i downgraded my hmmer at 3.3.0 and there is still empty output directory created after run. 
When i run phigaro with test_data/Bacillus_anthracis_str_ames.fna, it worked fine. 

Best wishes
Mia
