### ISSUE TITLE
db download :: download.ripcm.com/phigaro/ broken

### ISSUE THREAD

**Issue by EricDeveaud** [bobeobibo/phigaro#34]
Hello, 

can you provide a mirror of download.ripcm.com/phigaro/. 
google drive is not useable with command line tools. (wgat, curl) that breaks some automatic build mechanism of phigaro.

can you provide a wget-able (or curl-able) location for the dbs.

regards

Eric

**Comment by PollyTikhonova** [comment]
Hello, 
Currently, we have some issues on our servers, but we are trying to fix it. Generally it works.

But there is a way to download files from google drive using wget.
Here is tutorial how to do this: https://medium.com/@acpanjan/download-google-drive-files-using-wget-3c2c025a8b99

Here is the code to download database files separately:
`wget --load-cookies /tmp/cookies.txt "https://docs.google.com/uc?export=download&confirm=$(wget --quiet --save-cookies /tmp/cookies.txt --keep-session-cookies --no-check-certificate 'https://docs.google.com/uc?export=download&id=1tarima5Bzh523VbApnDevJzu1TieXcI2' -O- | sed -rn 's/.*confirm=([0-9A-Za-z_]+).*/\1\n/p')&id=1tarima5Bzh523VbApnDevJzu1TieXcI2" -O allpvoghmms.h3p && rm -rf /tmp/cookies.txt`

`wget --load-cookies /tmp/cookies.txt "https://docs.google.com/uc?export=download&confirm=$(wget --quiet --save-cookies /tmp/cookies.txt --keep-session-cookies --no-check-certificate 'https://docs.google.com/uc?export=download&id=17fVRygsC6-wq3QsBKGzOdsAX6B1qo998' -O- | sed -rn 's/.*confirm=([0-9A-Za-z_]+).*/\1\n/p')&id=17fVRygsC6-wq3QsBKGzOdsAX6B1qo998" -O allpvoghmms.h3m && rm -rf /tmp/cookies.txt`

`wget --load-cookies /tmp/cookies.txt "https://docs.google.com/uc?export=download&confirm=$(wget --quiet --save-cookies /tmp/cookies.txt --keep-session-cookies --no-check-certificate 'https://docs.google.com/uc?export=download&id=1fzp5phUybWAOWmhjwImEvA1lu1rcsxny' -O- | sed -rn 's/.*confirm=([0-9A-Za-z_]+).*/\1\n/p')&id=1fzp5phUybWAOWmhjwImEvA1lu1rcsxny" -O allpvoghmms.h3f && rm -rf /tmp/cookies.txt`

`wget --load-cookies /tmp/cookies.txt "https://docs.google.com/uc?export=download&confirm=$(wget --quiet --save-cookies /tmp/cookies.txt --keep-session-cookies --no-check-certificate 'https://docs.google.com/uc?export=download&id=1XSXgxeEZ6K5Ro6s797e9lmP55VCaSX1q' -O- | sed -rn 's/.*confirm=([0-9A-Za-z_]+).*/\1\n/p')&id=1XSXgxeEZ6K5Ro6s797e9lmP55VCaSX1q" -O allpvoghmms.h3i && rm -rf /tmp/cookies.txt`

`wget --load-cookies /tmp/cookies.txt "https://docs.google.com/uc?export=download&confirm=$(wget --quiet --save-cookies /tmp/cookies.txt --keep-session-cookies --no-check-certificate 'https://docs.google.com/uc?export=download&id=1BOdhn2dDPTHCVE9sCrK8H_sU69l-_SDm' -O- | sed -rn 's/.*confirm=([0-9A-Za-z_]+).*/\1\n/p')&id=1BOdhn2dDPTHCVE9sCrK8H_sU69l-_SDm" -O allpvoghmms && rm -rf /tmp/cookies.txt`

**Comment by PollyTikhonova** [comment]
I'll try to implement this into a setup process this weekend

**Comment by PollyTikhonova** [comment]
Hey, I just got the message that www.download.ripcm.com/phigaro/ works again!

**Comment by EricDeveaud** [comment]
thanks for this good news 
and sorry for the late reply.

Eric

**Comment by EricDeveaud** [comment]
Hummm not sure it is currently possible to download data from 
I have a `ERROR 403: Forbidden`

**Comment by PollyTikhonova** [comment]
Sorry, for answering only now.
There was a server maintenance at that day, since that time it works
http://download.ripcm.com/phigaro/
