### ISSUE TITLE
Output coordinates are off by 1

### ISSUE THREAD

**Issue by snystrom** [bobeobibo/phigaro#35]
Hi,

Thanks for the great tool. I noticed a minor bug in the gff3 and bed outputs where the start positions of genes are shifted 1 bp downstream. See example image below (expected start codon is AUG at this locus). 

![image](https://user-images.githubusercontent.com/17264973/138363222-e41887ad-9af9-4000-9529-705ca80f53a1.png)

I may be able to push a fix for this soon, but wanted to get your thoughts on implementation. It looks like the software in `batch/task/run_phigaro.py` is doing the correct math assuming 0-based indexing, so the input data must actually be 1-based coming out of `find_phages`? I guess there's 2 possible fixes: 1. alter find_phages behavior, or 2. adjust the coordinate shifting math in `run_phigaro.py`. I'm assuming fixing the shifting math is easier, but I wonder if there are other places in the codebase that make the 0-based indexing assumption.

Cheers,
  -Spencer

**Comment by PollyTikhonova** [comment]
Thanks for your contribution! we'll deal with it!

**Comment by PollyTikhonova** [comment]
I am happy to announce that this issue was fixed in phigaro 2.4.0
