### ISSUE TITLE
Html result file error

### ISSUE THREAD

**Issue by liuxiong714** [bobeobibo/phigaro#38]
Hi there!

Thank you to develop this helpful software! I've already successfully got the results using the Acinetobacter baumannii genome.
But in the html result file, I can only see the plot of the first prophage, and can not switch to the other predicted prophages list on the left.
my cammand was:
phigaro -f ../../02genome/njn001.fasta -o ./njn001/ -e tsv gff bed stdout html -t 12 -d -p --not-open

Could I get the plots of all prophages in the html file?

Thanks again,
Liu Xiong

**Comment by PollyTikhonova** [comment]
Answered via e-mail)
