### ISSUE TITLE
What is the latest version of phigaro ?

### ISSUE THREAD

**Issue by duboism** [bobeobibo/phigaro#43]
Hello,

I'm a bit lost in `phigaro` releases.

On github, the last tag is [v2.2.6](https://github.com/bobeobibo/phigaro/releases/tag/v2.2.6). However, on pypi, [v2.3.0](https://pypi.org/project/phigaro/2.3.0/) is available.

The date of the pypi package matches the date of a batch of commits but there has been a few commits since then. So I feel that a tag is missing on github: aea9469d09cdbfbb528998ebc43232ee9f44decd should be `v2.3.0`.

Any thoughts ?

**Comment by PollyTikhonova** [comment]
Thanks for noticing, I published the v2.3.0 to fix the descrepancy.
