### ISSUE TITLE
Can the location where the intermediate file is generated be changed to be inside the output file?

### ISSUE THREAD

**Issue by Dx-wmc** [bobeobibo/phigaro#44]
Hi, when I tried to run multiple Phigaro processes in parallel, I found that they only generated one intermediate directory 'proc'. This means that the output of the results will overlap and cause errors. Can you modify the program so that the intermediate directory is located in each outdir?

**Comment by PollyTikhonova** [comment]
Hi @Dx-wmc ! That's a good suggestion! I'll definetely try and implement the feature that you suggested, but, unfortunately, it will take time. As a temporarily decision, I would suggest to launch Phigaro from different folders, e.g. create folder for each task. Sorry for inconvenience...

**Comment by Dx-wmc** [comment]
Thank you for your consideration, I am looking forward to seeing this update in future versions.

**Comment by PollyTikhonova** [comment]
@Dx-wmc as I reviewed the issue, actually, despite the fact of only one folder generated, each run has it's unique token attached to the name of the input file, which prevents overwriting.
