### ISSUE TITLE
issues about output Files

### ISSUE THREAD

**Issue by qianxin-kxy** [bobeobibo/phigaro#46]
This is a very interesting and useful tool, but I have a question, which is the bed file in the output results, some of which have the following display
(phigaro) [kxy@zju Phigaro]$ cd /data/users/kxy/kxytry/assembleddata/analysis/phage/Phigaro/sp_2017_ST195_67074
(phigaro) [kxy@zju sp_2017_ST195_67074]$ more sp_2017_ST195_67074.phigaro.bed
##gff-version 3.2.1
NODE_34_length_35751_cov_67.7224 4909 9641 prophage1 . .
NODE_34_length_35751_cov_67.7224 15713 31032 prophage2 . .
NODE_34_length_35751_cov_67.7224 4909 5353 gene10 3.6e-84 -
NODE_34_length_35751_cov_67.7224 5546 5789 gene11 . +
NODE_34_length_35751_cov_67.7224 5795 5999 gene12 . -
NODE_34_length_35751_cov_67.7224 6137 6641 gene13 . -
NODE_34_length_35751_cov_67.7224 6642 7650 gene14 3.2e-194 -
NODE_34_length_35751_cov_67.7224 7701 7917 gene15 9.2e-52 -
NODE_34_length_35751_cov_67.7224 7931 8684 gene16 . -
NODE_34_length_35751_cov_67.7224 8987 9308 gene17 . +
NODE_34_length_35751_cov_67.7224 9369 9642 gene18 5.1e-54 +
NODE_34_length_35751_cov_67.7224 15713 16058 gene30 . +
NODE_34_length_35751_cov_67.7224 16266 16503 gene31 0.017 +
NODE_34_length_35751_cov_67.7224 17167 17623 gene32 . +
NODE_34_length_35751_cov_67.7224 17683 18118 gene33 7.3e-84 +

I want to know if there are no specific names for prophage1 and prophage2? Or is it a newly discovered prophage? Because I have hundreds of genomes to process and have already processed them, but I have to group them for statistics in the future. I don't know how to treat the prophages in the bed files corresponding to each genome。

In addition, are the following genes 10, 11, etc. bacteriophages or other special mobile components

**Comment by PollyTikhonova** [comment]
In version 2.4.0 I added taxonomy information about taxonomy to gff3 format. Also, this information was in `.tsv` and `.html `files of previous version of phigaro. We can't say for sure what are those genes, in `.tsv `and `.html `files you can see the lists of pvogs, for those genes that were matched. For some of those there are functions prediction (they are demonstrated in `.html`)
