### ISSUE TITLE
Cannot download fasta sequences

### ISSUE THREAD

**Issue by tauqeer9** [bobeobibo/phigaro#6]
Hi
This is a great tool, all steps work fine. However, I am not able to download the prophage sequences in fasta-format. The double-stranded DNA icon for BLAST works perfectly alright. But, the vertical arrow to download fasta sequences does not seem to work. In short, how can I extract fasta sequences of these prophage regions? Thanks.

**Comment by PollyTikhonova** [comment]
Hello, unfortunately, the server with the necessary script is down. But now the problem is fixed and the new version of phigaro is available now.  Also, you can change the line at header of your html file:
from `<script src="https://fastcdn.org/FileSaver.js/1.1.20151003/FileSaver.min.js"></script>` to
 `<script src="https://cdn.jsdelivr.net/gh/bobeobibo/phigaro/scripts/FileSaver.min.js"></script> `

**Comment by tauqeer9** [comment]
Thanks. It works fine now. However, it would be nice to save prophage sequences of each sample in the result folder automatically, along with phg and html files (prefix with sample name). For few samples it is easy to download these fasta files manually, but will be difficult if there are large number of samples to analyze. Just a thought.

**Comment by PollyTikhonova** [comment]
At the bottom of the html page you can find two icons: to blast all and to download all

**Comment by tauqeer9** [comment]
I am using this one-liner to generate phg and html files for 3 samples (In future, I plan to run on ~500 samples). Then, I open 3 html files to download their prophage fasta by clicking the download icon at the bottom corner, which is great.
Is it possible to add fasta download/generate feature with -e option? So it produce ".phg", ".html" and ".fasta" for each sample (accession number in this example), instead of downloading them manually from the html file. I think PHASTER tool produces fasta format sequence for each sample.

###############
 #!/bin/bash
files=('CP016072'
'CP016073'
'CP032682'
)
for file in "${files[@]}"; do
phigaro -f FASTA/${file}.fasta -o RESULT/${file}.phg -p --not-open -c config.yml -t 16 -e txt html
done
#############

Thank you so much.

**Comment by PollyTikhonova** [comment]
Hello! We've added the feature you asked about! Try it in a new Phigaro 0.2.1.7 =)

**Comment by tauqeer9** [comment]
Thank you so much. The newly added -s option downloads all the prophages in fasta format. It becomes easier to cluster all predicted prophages now. Thanks again for this great tool.

**Comment by tauqeer9** [comment]
Hello
I just updated to phigaro 2.2.6 using conda, and see that -s option to automatically download prophages in fasta format is no longer available. It would be nice to have this option for comparing all prophages. It is difficult to download them from the icon in the html file. Also, I can not find --wtp option with phigaro -h.

**Comment by PollyTikhonova** [comment]
Hello, sorry,
I'll check tomorrow when and why I lost the -s option and restore it!
About --wtp, it is a service option for WhatThePhage tool, so, it is not supposed for general usage
