### ISSUE TITLE
'Readme.md' couldn't be found during installation

### ISSUE THREAD

**Issue by LSTUGA** [bobeobibo/phigaro#8]
Downloading/unpacking phigaro
  Downloading phigaro-0.2.1.8-2.tar.gz (70kB): 70kB downloaded
  Running setup.py (path:/tmp/pip_build_root/phigaro/setup.py) egg_info for package phigaro
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/tmp/pip_build_root/phigaro/setup.py", line 2, in <module>
        with open("Readme.md", "r") as fh:
    FileNotFoundError: [Errno 2] No such file or directory: 'Readme.md'
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "/tmp/pip_build_root/phigaro/setup.py", line 2, in <module>

    with open("Readme.md", "r") as fh:

FileNotFoundError: [Errno 2] No such file or directory: 'Readme.md'

**Comment by PollyTikhonova** [comment]
Sorry, for a late reply. I repaired the package.  The actual version is phigaro-0.2.1.8-3.tar.gz
If pip uses the older version, type pip install phigaro --no-cache-dir

**Comment by PollyTikhonova** [comment]
Sorry, for a late reply. I repaired the package.  The actual version is phigaro-0.2.1.8-3.tar.gz
If pip uses the older version, type pip install phigaro --no-cache-dir
